services:
    db:
        container_name: postgres-db
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        image: wxn_postgres
        restart: always
        environment:
            POSTGRES_USER: $DB_USER
            POSTGRES_PASSWORD: $DB_PASS
            POSTGRES_DB: $DB_NAME
        ports:
            - $DB_PORT:5432
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
            - ./docker/postgres/config:/etc/postgresql

volumes:
    db:
