services:
    db:
        container_name: postgres-db
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        image: wxn_postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER?err}
            POSTGRES_PASSWORD: ${DB_PASS?err}
            POSTGRES_DB: ${DB_NAME?err}
        ports:
            - ${DB_PORT?err}:5432
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
            - ./docker/postgres/config:/etc/postgresql

volumes:
    db:
